name: Update readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'

jobs:
  update-waka:
    name: Update Wakatime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  update-recent-activity:
      runs-on: ubuntu-latest
      name: Update Github's recent activity

      steps:
        - uses: actions/checkout@v2
        - uses: jamesgeorge007/github-activity-readme@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}